name: Windows Build

on:
  pull_request:
    branches: [ slippi ]
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: "Build on Windows 10 64bit"
    runs-on: windows-latest
    steps:
      - name: "Remove Redistributable"
        shell: cmd
        run: |
          MsiExec.exe /passive /X{F0C3E5D1-1ADE-321E-8167-68EF0DE699A5}
                    
      - name: "Setup MSBuild"
        uses: microsoft/setup-msbuild@v1
                    
      - name: "Install DirectX Sdk"
        shell: cmd
        run: |
          choco install directx-sdk
      
      - name: "Checkout"
        uses: actions/checkout@v2.3.1
      
      - name: "Build via MSBuild"
        shell: cmd
        run: |
          msbuild /p:Configuration=Release /p:Platform=x64 ${{ github.workspace }}\Source\Dolphin.sln
        
